version: '3.12.1'
services:
  web:
    image: nginx:latest
    container_name: gather-bot-app  

  db:
    image: postgres:13
    container_name: gather-bot-db   
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword